# 


# How to create an empty and a full NumPy array?

In [1]:
import numpy as np
r = int(input("Enter no of rows ::  "))
c = int(input("Enter no of columns :: "))
arrE = np.empty((r, c), dtype=int)
print("Empty Array - ")
print(arrE)
arrF = np.full([r, c], 50, dtype=int)
print("\n Full Array")
print(arrF)

Enter no of rows ::  10
Enter no of columns :: 10
Empty Array - 
[[         -1  2147483647           1           0         824           0
            1           0         864           0]
 [        411     5570652         868           0         411     7929957
          880           0         411     7274595]
 [        892           0         411     6422633         908           0
          411     7209065         376           0]
 [        411     7602286        1072           0         411     6357093
         1120           0         411           0]
 [        324           0         411 -2147482880        1108           0
          411       32766        1096           0]
 [        411           0         864           0         411           0
          868           0         411           0]
 [        880           0         411           0         892           0
          411           0         908           0]
 [        411           0         376           0         41

# NumPy program to convert a list of numeric value into a one-dimensional NumPy array

In [1]:
import numpy as np
l = [1,2,3,4,5]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)
l = [[1,2],[2,3],[3,4]]
print("Original List:",l)
a = np.array(l)
print("Two-dimensional NumPy array: ",a)


Original List: [1, 2, 3, 4, 5]
One-dimensional NumPy array:  [1 2 3 4 5]
Original List: [[1, 2], [2, 3], [3, 4]]
Two-dimensional NumPy array:  [[1 2]
 [2 3]
 [3 4]]


# NumPy program to create an array with values range

In [3]:
import numpy as np
n1 = int(input("Enter Start Range :: "))
n2 = int(input("Enter End Range :: "))

arr = np.arange(n1,n2+1)
print(arr)

Enter Start Range :: 1
Enter End Range :: 10
[ 1  2  3  4  5  6  7  8  9 10]


# NumPy program to get the numpy version and show numpy build configuration

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
None


# NumPy program to create an array of 5 zeros,5 ones, 5 fives

In [3]:
import numpy as np
array=np.zeros(5)
print("zeros array ::")
print(array)
array=np.ones(5)
print("ones array ::")
print(array)
array=np.full(5, 5)
print("fives:")
print(array)

zeros array ::
[0. 0. 0. 0. 0.]
ones array ::
[1. 1. 1. 1. 1.]
fives:
[5 5 5 5 5]


# Write a NumPy program to convert a list and tuple into arrays

In [2]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ") 
print(np.asarray(my_list))
my_tuple = ([1, 2, 3], [11, 12, 13])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[ 1  2  3]
 [11 12 13]]


# NumPy program to append values to the end of an array.

In [4]:
# Using Append 
import numpy as np
arr = [10, 20, 30]
print("Original array:")
print(arr)
arr = np.append(arr, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(arr)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [10]:
# using concatenate()
import numpy as np
arr = [10, 20, 30]
print("Original array:")
print(arr)
arr = np.concatenate((arr, [70, 80, 90]))
print("After append values to the end of the array:")
print(arr)


Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 70 80 90]


# NumPy program to get the unique elements of an array

In [13]:
import numpy as np
print("1D Array")
arr = np.array([10, 10, 15, 20, 20, 30, 30, 35])
print("Original array:" , arr)
print("Unique Elements: ", np.unique(arr))
print("2D Array : ")
arr = np.array([[1, 1, 2 , 5], [2, 3, 4, 6]])
print("Original array:" , arr)
print("Unique elements :", np.unique(arr))

1D Array
Original array: [10 10 15 20 20 30 30 35]
Unique Elements:  [10 15 20 30 35]
2D Array : 
Original array: [[1 1 2 5]
 [2 3 4 6]]
Unique elements : [1 2 3 4 5 6]


# How to check if a NumPy array is empty in Python?

In [19]:
import numpy as np
 
arr = np.array([])
if(arr.size == 0):
    print("Is Empty")
else:
    print("Not Empty")
arr = np.array([1, 2, 3])
if(arr.size == 0):
    print("is_empty")
else:
    print("Not Empty")

Is Empty
Not Empty


# NumPy program to test whether all elements in an array evaluate to True

In [22]:
import numpy as np
 
thearr = [[True, False], [True, True]]
thebool = np.all(thearr)
print(thebool)
 
thearr = [[False, False], [False, False]]
thebool = np.all(thearr)
print(thebool)

a =10
thearr = [[a>10, a==10],[a<10, a>=10]]
thebool = np.all(thearr)
print(thebool)

False
False
False


# NumPy program to test whether any elements in an array evaluate to True

In [30]:
import numpy as np
 
thearr = [[True, False], [True, True]]
thebool = np.any(thearr)
print(thebool)
 
thearr = [[False, False], [False, False]]
thebool = np.any(thearr)
print(thebool)

a =10
thearr = [[a>10, a==10],[a<10, a>=10]]
thebool = np.any(thearr)
print(thebool)

True
False
True


# Numpy Program to remove nan values

In [32]:

import numpy as np
 
arr  = np.array([np.nan, 2, 3, 4])
arr  = arr [~np.isnan(arr)]
print(arr)

[2. 3. 4.]


# Numpy Program to remove nan values from multidimention array

In [34]:
import numpy as np
 
arr  = np.array([[np.nan, 2, 3, 4],[1,2,np.nan,4]])
arr  = arr [~np.isnan(arr)]
print(arr)

[2. 3. 4. 1. 2. 4.]
