# 


# How to create an empty and a full NumPy array?

In [1]:
import numpy as np
r = int(input("Enter no of rows ::  "))
c = int(input("Enter no of columns :: "))
arrE = np.empty((r, c), dtype=int)
print("Empty Array - ")
print(arrE)
arrF = np.full([r, c], 50, dtype=int)
print("\n Full Array")
print(arrF)

Enter no of rows ::  10
Enter no of columns :: 10
Empty Array - 
[[         -1  2147483647           1           0         824           0
            1           0         864           0]
 [        411     5570652         868           0         411     7929957
          880           0         411     7274595]
 [        892           0         411     6422633         908           0
          411     7209065         376           0]
 [        411     7602286        1072           0         411     6357093
         1120           0         411           0]
 [        324           0         411 -2147482880        1108           0
          411       32766        1096           0]
 [        411           0         864           0         411           0
          868           0         411           0]
 [        880           0         411           0         892           0
          411           0         908           0]
 [        411           0         376           0         41

# NumPy program to get the numpy version and show numpy build configuration

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/keyco/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/keyco/anaconda3\\Library\\include']
None


# NumPy program to create an array of 5 zeros,5 ones, 5 fives

In [3]:
import numpy as np
array=np.zeros(5)
print("zeros array ::")
print(array)
array=np.ones(5)
print("ones array ::")
print(array)
array=np.full(5, 5)
print("fives:")
print(array)

zeros array ::
[0. 0. 0. 0. 0.]
ones array ::
[1. 1. 1. 1. 1.]
fives:
[5 5 5 5 5]
