# advance slicing

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 0]])




[1 4 5]


In [4]:
import numpy as np
x = np.array([[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
           [ 9, 10, 11]])
rows = np.array([[0, 0],[3, 3]], dtype=np.intp)
columns = np.array([[0, 2],[0, 1]], dtype=np.intp)
print(x[rows, columns])


[[ 0  2]
 [ 9 10]]


In [5]:
import numpy as np
x = np.array([[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
           [ 9, 10, 11]])
print(x[1:2,1:3])
print(x[1:2,[1,2]])

[[4 5]]
[[4 5]]


# Boolean Array indexing

In [6]:
import numpy as np
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

In [7]:
import numpy as np
x = np.array([1., -1., -2., 3])
x[x < 0] 

array([-1., -2.])

In [9]:
import numpy as np
x = np.array([1., -1., -2., 3])
x = x[x < 0] + 10
print(x)

[9. 8.]


In [16]:
import numpy as np
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
print(rowsum)
print(x[rowsum <= 2, :])
colsum = x.sum(0)
print(colsum)
print(x[ :, colsum >3])

[1 2 4]
[[0 1]
 [1 1]]
[3 4]
[[1]
 [1]
 [2]]


In [21]:
import numpy as np
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])
print(a)
print("A = " ,a['a'])
print("B = ", a['b'])
import numpy as np
a = np.array([(0, 1, 4.) ,(40, 10, 10.), (0, 30, 0.)], dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])
print(a)
print("A = " ,a['a'])
print("B = ", a['b'])

[(0, 0, 0.) (0, 0, 0.) (0, 0, 0.)]
A =  [0 0 0]
B =  [0 0 0]
[( 0,  1,  4.) (40, 10, 10.) ( 0, 30,  0.)]
A =  [ 0 40  0]
B =  [ 1 10 30]


# Flat iterator

In [29]:
x = np.arange(6).reshape(2, 3)
print(x.flat[3]) 
fl = x.flat
print(fl)
for i in fl:
    print(i)
print(type(fl))


print(x.T)
print(x.T.flat[3])

3
0
1
2
3
4
5
<class 'numpy.flatiter'>
[[0 3]
 [1 4]
 [2 5]]
4


# Brodcasting

In [11]:
L1= [1,2,3]
L2 = [4,5,6]
print(L1 + L2)
print(L1+3)

[1, 2, 3, 4, 5, 6]


TypeError: can only concatenate list (not "int") to list

In [6]:
import numpy as np
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40,50]) 
c = a * b 
print(c)

[ 10  40  90 160]


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [4]:
# Single Dimension array 

import numpy as np
a = np.array([10 ,11, 12]) # 1x3 Dimension array
print(a)
b = 10 
print(b)
c = a + b
print(c)

[10 11 12]
10
[20 21 22]


In [5]:
#Two Dimensional Array 
import numpy as np
A = np.array([[10, 11, 12], [21, 22, 23]])
print(A)
b = 2
print(b)
 
C = A + b
print(C)

[[10 11 12]
 [21 22 23]]
2
[[12 13 14]
 [23 24 25]]


In [8]:
#
import numpy as np  
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)  
print("\nprinting array b..")  
print(b)  
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c)  


printing array a..
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 6  9 12 15]
 [ 9 12 15 18]]
