In [3]:
## handling nan  - print true / false 
import numpy as np
 
x = np.array([np.nan, 2, 3, 4])
print(np.isnan(x))



[ True False False False]


In [4]:
# print values except nan values
import numpy as np
 
x = np.array([np.nan, 2, 3, 4])

x = x[~np.isnan(x)]
print(x)

[2. 3. 4.]


In [7]:
# handling nan in 2-D Array 
import numpy as np
x = np.array([[1, 2, np.nan, 4], 
                 [2, 3, 4, np.nan],
                 [np.nan, 5,np.nan, 6]])
print(x[~(np.isnan(x))])

[1. 2. 4. 2. 3. 4. 5. 6.]


In [8]:
### using isnan() and logical_not() 

import numpy as np

x= np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
x = x[np.logical_not(np.isnan(x))] 
print(x)


[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:

import numpy as np

x= np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
x = x[~np.isnan(x)]
print(x)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [12]:
# using isfinite() function

import numpy as np
x = np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
print("Finite : ", np.isfinite(1))
print("Finite : ", np.isfinite(0))
# not a number
print("Finite : ", np.isfinite(np.nan))
#  infinity
print("Finite : ", np.isfinite(np.inf))
print("Finite : ", np.isfinite(np.NINF))

Finite :  True
Finite :  True
Finite :  False
Finite :  False
Finite :  False


In [13]:

import numpy as np
x1 = np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
x2 = np.array([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])
x3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x1[np.isfinite(x1)])
print(x2[np.isfinite(x2)])
print(x3[np.isfinite(x3)])


[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[]
[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# using math.nan function
import math
print (math.isnan (56))
print (math.isnan (-45))
print (math.isnan (+45.34))
print (math.isnan (math.inf))
print (math.isnan (float("nan")))
print (math.isnan (float("inf")))
print (math.isnan (float("-inf")))
print (math.isnan (math.nan))

False
False
False
False
True
False
False
True


In [16]:
import math
import numpy as np
x1 = np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
x2 = np.array([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])
x3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b1 = [not math.isnan(number) for number in x1]
b2 = [not math.isnan(number) for number in x2]
b3 = [not math.isnan(number) for number in x3]
print(b1)
print(b2)
print(b3)

[True, True, True, False, False, True, True, True, False, True, True, True, False]
[False, False, False, False, False, False]
[True, True, True, True, True, True, True, True, True, True]


In [18]:
import math
import numpy as np
x1 = np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
x2 = np.array([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])
x3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b1 = x1[[not math.isnan(number) for number in x1]]
b2 = x2[[not math.isnan(number) for number in x2]]
b3 = x3[[not math.isnan(number) for number in x3]]
print(b1)
print(b2)
print(b3)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[]
[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# pandas isnull()

import numpy as np
import pandas as pd

x1 = np.array([1, 2, 3, np.nan, np.nan, 4, 5, 6, np.nan, 7, 8, 9, np.nan])
x2 = np.array([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])
x3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b1 = x1[[not pd.isnull(number) for number in x1]]
b2 = x2[[not pd.isnull(number) for number in x2]]
b3 = x3[[not pd.isnull(number) for number in x3]]
print(b1)
print(b2)
print(b3)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[]
[ 1  2  3  4  5  6  7  8  9 10]
