In [10]:
#Relational operators
import numpy as np
arr1 = np.array([30,23,67,12,8,9,4])
arr1[arr1 > 30] = 100
print(arr1)


[ 30  23 100  12   8   9   4]


In [1]:
# Program to replace items that satisfy a condition with another value in Numpy array?

In [5]:
import numpy as np
arr1 = np.array([30,23,67,12,8,9,4])
 
result1 = np.where(arr1 > 20, 0, arr1)  # replace with zero 
print(result1)

result2 = np.where(arr1 > 20, 100, arr1) # replace with 100
print(result2)



[ 0  0  0 12  8  9  4]
[100 100 100  12   8   9   4]


In [7]:
# Program to replace items thats between number1 and number 2
import numpy as np
arr1 = np.array([30,23,67,12,8,9,4])
 
result1 = np.where( (arr1 > 20) & (arr1 < 30), 0, arr1)  # replace with zero 
print(result1)

[30  0 67 12  8  9  4]


In [8]:
# Replace all elements of array which satisfy the condition with 1 otherwise 0
import numpy as np
arr1 = np.array([30,23,67,12,8,9,4])
 
result1 = an_array = np.asarray([0 if val < 30 else 1 for val in the_array])
print(result1)


[1 0 1 0 0 0 0]


In [9]:
# Replace all elements of an array with Nan value 

import numpy as np
 
arr1 = np.array([30,23,67,12,8,9,4])
 
result1 = np.where(arr1 > 25, np.NaN, arr1)
print(result1)

[nan 23. nan 12.  8.  9.  4.]
